-- Insertar las 11 sedes desde los datos actuales del código
-- Ejecutar en SQL Editor de Supabase

INSERT INTO sedes (slug, name, tipo, location, students, img, description, infra) VALUES
('liceo-principal', 'Liceo Ignacio Yepes Yepes', 'Urbana', 'Zona urbana, Remedios, Antioquia', 1000, 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&q=80', '["Sede principal de la institución y eje articulador de todo el proyecto educativo. Atiende los niveles de básica secundaria y media, formando jóvenes con sólidos valores académicos, humanos y ciudadanos.", "Cuenta con la infraestructura más amplia del municipio, espacios deportivos, laboratorios y una comunidad educativa comprometida con la excelencia."]'::jsonb, '{"salones":28,"cancha":true,"informatica":true,"extras":["Biblioteca","Laboratorio de ciencias","Auditorio"]}'::jsonb),

('eu-remedios', 'E.U. Remedios', 'Urbana', 'Casco urbano, Remedios, Antioquia', 300, 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=1200&q=80', '["Escuela urbana dedicada a la formación de niños y niñas en preescolar y básica primaria, ubicada estratégicamente en el centro del municipio.", "Su enfoque pedagógico promueve la lectura, el juego y el desarrollo de competencias básicas en un ambiente cálido y seguro."]'::jsonb, '{"salones":12,"cancha":true,"informatica":true,"extras":["Restaurante escolar"]}'::jsonb),

('eu-santa-teresita', 'E.U. Santa Teresita', 'Urbana', 'Barrio Santa Teresita, Remedios', 250, 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&q=80', '["Sede urbana que acompaña la primera infancia y la básica primaria en el barrio Santa Teresita, con una propuesta cercana a las familias.", "Trabaja por una educación inclusiva, fortaleciendo los valores, la convivencia y las competencias comunicativas."]'::jsonb, '{"salones":10,"cancha":true,"informatica":true}'::jsonb),

('cer-la-ceiba', 'C.E.R. La Ceiba', 'Rural', 'Vereda La Ceiba, Remedios', 120, 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&q=80', '["Centro educativo rural ubicado en la vereda La Ceiba, donde se imparte preescolar y básica primaria bajo el modelo de Escuela Nueva.", "Su quehacer pedagógico integra el contexto campesino, promoviendo el respeto por la tierra, la familia y el trabajo comunitario."]'::jsonb, '{"salones":4,"cancha":true,"informatica":false,"extras":["Huerta escolar"]}'::jsonb),

('cer-la-cruz', 'C.E.R. La Cruz', 'Rural', 'Vereda La Cruz, Remedios', 100, 'https://images.unsplash.com/photo-1488190211105-8a0e65b04d4e?w=1200&q=80', '["Sede rural que brinda educación preescolar y primaria a los niños y niñas de la vereda La Cruz y comunidades cercanas.", "Promueve la formación en valores, el cuidado del medio ambiente y el arraigo por las tradiciones campesinas."]'::jsonb, '{"salones":3,"cancha":true,"informatica":false}'::jsonb),

('cer-la-gorgona', 'C.E.R. La Gorgona', 'Rural', 'Vereda La Gorgona, Remedios', 90, 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&q=80', '["Centro educativo rural que atiende a la población infantil de la vereda La Gorgona con metodología flexible adaptada al contexto rural.", "Su propuesta combina el aprendizaje académico con proyectos productivos y ambientales propios de la zona."]'::jsonb, '{"salones":3,"cancha":true,"informatica":true}'::jsonb),

('cer-canaveral', 'C.E.R. Cañaveral', 'Rural', 'Vereda Cañaveral, Remedios', 80, 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=1200&q=80', '["Sede rural enclavada en la vereda Cañaveral, comprometida con una educación pertinente y de calidad para la niñez campesina.", "Fomenta valores como la solidaridad, el esfuerzo y la responsabilidad, en estrecha relación con las familias del territorio."]'::jsonb, '{"salones":3,"cancha":true,"informatica":false}'::jsonb),

('cer-el-popero', 'C.E.R. El Popero', 'Rural', 'Vereda El Popero, Remedios', 70, 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80', '["Centro educativo de la vereda El Popero que ofrece formación primaria con un enfoque centrado en el estudiante y su entorno.", "Trabaja por el fortalecimiento de la lectura, la escritura y el pensamiento lógico desde los primeros años escolares."]'::jsonb, '{"salones":2,"cancha":true,"informatica":false}'::jsonb),

('cer-martana', 'C.E.R. Martaná', 'Rural', 'Vereda Martaná, Remedios', 60, 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&q=80', '["Sede rural que acompaña a los niños y niñas de la vereda Martaná en su proceso de formación inicial y básica primaria.", "Su propuesta pedagógica resalta el valor de la comunidad, la cultura local y la convivencia pacífica."]'::jsonb, '{"salones":2,"cancha":true,"informatica":false}'::jsonb),

('cer-paso-de-la-mula', 'C.E.R. Paso de la Mula', 'Rural', 'Vereda Paso de la Mula, Remedios', 65, 'https://images.unsplash.com/photo-1488190211105-8a0e65b04d4e?w=1200&q=80', '["Centro educativo rural de la vereda Paso de la Mula, que ofrece educación preescolar y básica primaria a la población campesina de la zona.", "Su propuesta pedagógica fortalece la identidad territorial, el trabajo en equipo y las competencias básicas de los estudiantes rurales."]'::jsonb, '{"salones":2,"cancha":true,"informatica":false}'::jsonb),

('cer-santa-lucia', 'C.E.R. Santa Lucía', 'Rural', 'Vereda Santa Lucía, Remedios', 70, 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&q=80', '["Sede rural ubicada en la vereda Santa Lucía, comprometida con la formación integral de niños y niñas en preescolar y básica primaria.", "Integra el aprendizaje académico con proyectos productivos como la huerta escolar, fomentando el amor por la tierra y el trabajo comunitario."]'::jsonb, '{"salones":2,"cancha":true,"informatica":false,"extras":["Huerta escolar"]}'::jsonb)
ON CONFLICT (slug) DO NOTHING;
